# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: game.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\ngame.proto\"\x07\n\x05\x45mpty\".\n\x07Soldier\x12\t\n\x01x\x18\x01 \x01(\x05\x12\t\n\x01y\x18\x02 \x01(\x05\x12\r\n\x05speed\x18\x03 \x01(\x05\",\n\x07Missile\x12\t\n\x01x\x18\x01 \x01(\x05\x12\t\n\x01y\x18\x02 \x01(\x05\x12\x0b\n\x03rad\x18\x03 \x01(\x05\"\x1f\n\x0cServerOutput\x12\x0f\n\x07message\x18\x01 \x01(\t\"\x1a\n\x07Request\x12\x0f\n\x07message\x18\x01 \x01(\t\"\x1b\n\x08Response\x12\x0f\n\x07message\x18\x01 \x01(\t2\xda\x01\n\x04Game\x12%\n\x08register\x12\x08.Soldier\x1a\r.ServerOutput\"\x00\x12(\n\x10missile_approach\x12\x06.Empty\x1a\x08.Missile\"\x00\x30\x01\x12\x1c\n\x06status\x12\x08.Request\x1a\x06.Empty\"\x00\x12$\n\tbroadcast\x12\x08.Request\x1a\t.Response\"\x00\x30\x01\x12\x1e\n\x05unary\x12\x08.Request\x1a\t.Response\"\x00\x12\x1d\n\x0bsendMissile\x12\x06.Empty\x1a\x06.Emptyb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'game_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _globals['_EMPTY']._serialized_start=14
  _globals['_EMPTY']._serialized_end=21
  _globals['_SOLDIER']._serialized_start=23
  _globals['_SOLDIER']._serialized_end=69
  _globals['_MISSILE']._serialized_start=71
  _globals['_MISSILE']._serialized_end=115
  _globals['_SERVEROUTPUT']._serialized_start=117
  _globals['_SERVEROUTPUT']._serialized_end=148
  _globals['_REQUEST']._serialized_start=150
  _globals['_REQUEST']._serialized_end=176
  _globals['_RESPONSE']._serialized_start=178
  _globals['_RESPONSE']._serialized_end=205
  _globals['_GAME']._serialized_start=208
  _globals['_GAME']._serialized_end=426
# @@protoc_insertion_point(module_scope)
